In [1]:
import pandas as pd

In [2]:
data = pd.read_csv("misdata.csv")

In [3]:
data

                nombre
0          Kelly Lewis
1         Sara Herrera
2        Brianna Grant
3      Dr. Dana Joseph
4         Beth Edwards
5       Theresa Davila
6        Daniel Newman
7          Bryan Allen
8        Jerry Elliott
9       Robert Barnett
10     Robert Williams
11       Kerri Estrada
12          Eric Rivas
13       Devon Kennedy
14        Andrea Parks
15        Amanda Lopez
16      Olivia Fleming
17        Suzanne Lane
18      Rachel Fleming
19  Amanda Christensen
20         Jack Brewer
21       James Oconnor
22        Susan Austin
23   Melanie Whitehead
24        Joseph Lyons
25     Glenn Lewis DVM
26  Christopher Torres
27        Jon Matthews
28      George Higgins
29        Amanda Young
30       Jeffrey White
31      Steven Shelton
32     Kristina Strong
33   Rachel Herrera MD
34      Angela Farrell
35         Ashley Hays
36         Jon Johnson
37     William Shepard
38    David Washington
39     Hunter Gonzales
40      Miguel Jenkins
41       Michael Arias
42  Jeffrey Richardson
43    Anthony Melendez
44     Heather Collins
45      Jamie Johnston
46     Deborah Roberts
47         Jill Morgan
48      Rebecca Fowler
49      Jessica Miller
50        Larry Howell

In [4]:
def obtener_inicial(d):
    cadena = d[0]
    return cadena

In [5]:
def obtener_mayuscula(d):
    cadena = d.upper()
    return cadena

In [6]:
data['inicial'] = data['nombre'].apply(obtener_inicial)

In [7]:
data

                nombre inicial
0          Kelly Lewis       K
1         Sara Herrera       S
2        Brianna Grant       B
3      Dr. Dana Joseph       D
4         Beth Edwards       B
5       Theresa Davila       T
6        Daniel Newman       D
7          Bryan Allen       B
8        Jerry Elliott       J
9       Robert Barnett       R
10     Robert Williams       R
11       Kerri Estrada       K
12          Eric Rivas       E
13       Devon Kennedy       D
14        Andrea Parks       A
15        Amanda Lopez       A
16      Olivia Fleming       O
17        Suzanne Lane       S
18      Rachel Fleming       R
19  Amanda Christensen       A
20         Jack Brewer       J
21       James Oconnor       J
22        Susan Austin       S
23   Melanie Whitehead       M
24        Joseph Lyons       J
25     Glenn Lewis DVM       G
26  Christopher Torres       C
27        Jon Matthews       J
28      George Higgins       G
29        Amanda Young       A
30       Jeffrey White       J
31      Steven Shelton       S
32     Kristina Strong       K
33   Rachel Herrera MD       R
34      Angela Farrell       A
35         Ashley Hays       A
36         Jon Johnson       J
37     William Shepard       W
38    David Washington       D
39     Hunter Gonzales       H
40      Miguel Jenkins       M
41       Michael Arias       M
42  Jeffrey Richardson       J
43    Anthony Melendez       A
44     Heather Collins       H
45      Jamie Johnston       J
46     Deborah Roberts       D
47         Jill Morgan       J
48      Rebecca Fowler       R
49      Jessica Miller       J
50        Larry Howell       L

In [8]:
data['mayuscula'] = data['nombre'].apply(obtener_mayuscula)

In [9]:
data

                nombre inicial           mayuscula
0          Kelly Lewis       K         KELLY LEWIS
1         Sara Herrera       S        SARA HERRERA
2        Brianna Grant       B       BRIANNA GRANT
3      Dr. Dana Joseph       D     DR. DANA JOSEPH
4         Beth Edwards       B        BETH EDWARDS
5       Theresa Davila       T      THERESA DAVILA
6        Daniel Newman       D       DANIEL NEWMAN
7          Bryan Allen       B         BRYAN ALLEN
8        Jerry Elliott       J       JERRY ELLIOTT
9       Robert Barnett       R      ROBERT BARNETT
10     Robert Williams       R     ROBERT WILLIAMS
11       Kerri Estrada       K       KERRI ESTRADA
12          Eric Rivas       E          ERIC RIVAS
13       Devon Kennedy       D       DEVON KENNEDY
14        Andrea Parks       A        ANDREA PARKS
15        Amanda Lopez       A        AMANDA LOPEZ
16      Olivia Fleming       O      OLIVIA FLEMING
17        Suzanne Lane       S        SUZANNE LANE
18      Rachel Fleming       R      RACHEL FLEMING
19  Amanda Christensen       A  AMANDA CHRISTENSEN
20         Jack Brewer       J         JACK BREWER
21       James Oconnor       J       JAMES OCONNOR
22        Susan Austin       S        SUSAN AUSTIN
23   Melanie Whitehead       M   MELANIE WHITEHEAD
24        Joseph Lyons       J        JOSEPH LYONS
25     Glenn Lewis DVM       G     GLENN LEWIS DVM
26  Christopher Torres       C  CHRISTOPHER TORRES
27        Jon Matthews       J        JON MATTHEWS
28      George Higgins       G      GEORGE HIGGINS
29        Amanda Young       A        AMANDA YOUNG
30       Jeffrey White       J       JEFFREY WHITE
31      Steven Shelton       S      STEVEN SHELTON
32     Kristina Strong       K     KRISTINA STRONG
33   Rachel Herrera MD       R   RACHEL HERRERA MD
34      Angela Farrell       A      ANGELA FARRELL
35         Ashley Hays       A         ASHLEY HAYS
36         Jon Johnson       J         JON JOHNSON
37     William Shepard       W     WILLIAM SHEPARD
38    David Washington       D    DAVID WASHINGTON
39     Hunter Gonzales       H     HUNTER GONZALES
40      Miguel Jenkins       M      MIGUEL JENKINS
41       Michael Arias       M       MICHAEL ARIAS
42  Jeffrey Richardson       J  JEFFREY RICHARDSON
43    Anthony Melendez       A    ANTHONY MELENDEZ
44     Heather Collins       H     HEATHER COLLINS
45      Jamie Johnston       J      JAMIE JOHNSTON
46     Deborah Roberts       D     DEBORAH ROBERTS
47         Jill Morgan       J         JILL MORGAN
48      Rebecca Fowler       R      REBECCA FOWLER
49      Jessica Miller       J      JESSICA MILLER
50        Larry Howell       L        LARRY HOWELL

In [10]:
data.to_csv("misdata2.csv")