In [1]:
import pandas as pd

In [4]:
pip install faker

Collecting faker
  Downloading Faker-24.11.0-py3-none-any.whl.metadata (15 kB)
Requirement already satisfied: python-dateutil>=2.4 in d:\users\fabricio\documents\maestria\python\lib\site-packages (from faker) (2.9.0.post0)
Requirement already satisfied: six>=1.5 in d:\users\fabricio\documents\maestria\python\lib\site-packages (from python-dateutil>=2.4->faker) (1.16.0)
Downloading Faker-24.11.0-py3-none-any.whl (1.8 MB)
   ---------------------------------------- 0.0/1.8 MB ? eta -:--:--
   -- ------------------------------------- 0.1/1.8 MB 1.8 MB/s eta 0:00:01
   ---- ----------------------------------- 0.2/1.8 MB 2.2 MB/s eta 0:00:01
   -------- ------------------------------- 0.4/1.8 MB 2.9 MB/s eta 0:00:01
   ------------- -------------------------- 0.6/1.8 MB 3.4 MB/s eta 0:00:01
   ------------------ --------------------- 0.8/1.8 MB 3.6 MB/s eta 0:00:01
   ------------------- -------------------- 0.8/1.8 MB 3.2 MB/s eta 0:00:01
   -------------------- ------------------- 0.9/1.8 MB 2.9 MB/s eta 0:00:01
   ------------------------ --------------- 1.1/1.8 MB 2.9 MB/s eta 0:00:01
   ---------------------------- ----------- 1.2/1.8 MB 3.0 MB/s eta 0:00:01
   -------------------------------- ------- 1.4/1.8 MB 3.2 MB/s eta 0:00:01
   ----------------------------------- ---- 1.6/1.8 MB 3.1 MB/s eta 0:00:01
   ------------------------------------- -- 1.7/1.8 MB 3.0 MB/s eta 0:00:01
   ---------------------------------------  1.8/1.8 MB 3.0 MB/s eta 0:00:01
   ---------------------------------------- 1.8/1.8 MB 2.9 MB/s eta 0:00:00
Installing collected packages: faker
Successfully installed faker-24.11.0
Note: you may need to restart the kernel to use updated packages.

In [5]:
from faker import Faker
fake = Faker()

In [6]:
lista = []

In [7]:
for x in range(0,51):
    lista.append({'nombre': fake.name()})

In [8]:
lista

[{'nombre': 'Kelly Lewis'},
 {'nombre': 'Sara Herrera'},
 {'nombre': 'Brianna Grant'},
 {'nombre': 'Dr. Dana Joseph'},
 {'nombre': 'Beth Edwards'},
 {'nombre': 'Theresa Davila'},
 {'nombre': 'Daniel Newman'},
 {'nombre': 'Bryan Allen'},
 {'nombre': 'Jerry Elliott'},
 {'nombre': 'Robert Barnett'},
 {'nombre': 'Robert Williams'},
 {'nombre': 'Kerri Estrada'},
 {'nombre': 'Eric Rivas'},
 {'nombre': 'Devon Kennedy'},
 {'nombre': 'Andrea Parks'},
 {'nombre': 'Amanda Lopez'},
 {'nombre': 'Olivia Fleming'},
 {'nombre': 'Suzanne Lane'},
 {'nombre': 'Rachel Fleming'},
 {'nombre': 'Amanda Christensen'},
 {'nombre': 'Jack Brewer'},
 {'nombre': 'James Oconnor'},
 {'nombre': 'Susan Austin'},
 {'nombre': 'Melanie Whitehead'},
 {'nombre': 'Joseph Lyons'},
 {'nombre': 'Glenn Lewis DVM'},
 {'nombre': 'Christopher Torres'},
 {'nombre': 'Jon Matthews'},
 {'nombre': 'George Higgins'},
 {'nombre': 'Amanda Young'},
 {'nombre': 'Jeffrey White'},
 {'nombre': 'Steven Shelton'},
 {'nombre': 'Kristina Strong'},
 {'nombre': 'Rachel Herrera MD'},
 {'nombre': 'Angela Farrell'},
 {'nombre': 'Ashley Hays'},
 {'nombre': 'Jon Johnson'},
 {'nombre': 'William Shepard'},
 {'nombre': 'David Washington'},
 {'nombre': 'Hunter Gonzales'},
 {'nombre': 'Miguel Jenkins'},
 {'nombre': 'Michael Arias'},
 {'nombre': 'Jeffrey Richardson'},
 {'nombre': 'Anthony Melendez'},
 {'nombre': 'Heather Collins'},
 {'nombre': 'Jamie Johnston'},
 {'nombre': 'Deborah Roberts'},
 {'nombre': 'Jill Morgan'},
 {'nombre': 'Rebecca Fowler'},
 {'nombre': 'Jessica Miller'},
 {'nombre': 'Larry Howell'}]

In [9]:
data = pd.DataFrame(lista)

In [10]:
data

                nombre
0          Kelly Lewis
1         Sara Herrera
2        Brianna Grant
3      Dr. Dana Joseph
4         Beth Edwards
5       Theresa Davila
6        Daniel Newman
7          Bryan Allen
8        Jerry Elliott
9       Robert Barnett
10     Robert Williams
11       Kerri Estrada
12          Eric Rivas
13       Devon Kennedy
14        Andrea Parks
15        Amanda Lopez
16      Olivia Fleming
17        Suzanne Lane
18      Rachel Fleming
19  Amanda Christensen
20         Jack Brewer
21       James Oconnor
22        Susan Austin
23   Melanie Whitehead
24        Joseph Lyons
25     Glenn Lewis DVM
26  Christopher Torres
27        Jon Matthews
28      George Higgins
29        Amanda Young
30       Jeffrey White
31      Steven Shelton
32     Kristina Strong
33   Rachel Herrera MD
34      Angela Farrell
35         Ashley Hays
36         Jon Johnson
37     William Shepard
38    David Washington
39     Hunter Gonzales
40      Miguel Jenkins
41       Michael Arias
42  Jeffrey Richardson
43    Anthony Melendez
44     Heather Collins
45      Jamie Johnston
46     Deborah Roberts
47         Jill Morgan
48      Rebecca Fowler
49      Jessica Miller
50        Larry Howell

In [11]:
data.to_csv("misdata.csv", index=False)